### ISSUE TITLE
Add requester user account to ebay-account object

### ISSUE THREAD

**Issue by gerpaick** [luke-dixon/django-ebay-accounts#2]
I was wondering if it is worth to add another field to ebay-account model. It would be good to have also the 'owner' ow created ebay-account. So, many users can have many ebay-accounts.
What do you think?

**Comment by luke-dixon** [comment]
Nice idea.
I had wanted to do something like this for a while, so each user or group could have ebay accounts associated with them.
You could do that now by creating a new app with a Model with a OneToOneField for the ebay account and a ForeignKey to the user model or group model.
I'm not sure whether it is a good idea or not to include those models here or just perhaps document them somewhere. Perhaps I'll take a look at some other Django apps and see if any do anything similar.
Even if we don't include the models, it would be nice to make sure the views can be easily extended to support this.

**Comment by gerpaick** [comment]
I've done it not in best way, but maybe someone will have use of it.
in models.py:
`from django.contrib.auth.models import User`
and in `class Account(models.Model): ` i added:
`account =  models.ForeignKey(User)`

then in `views.py` in `class AccountFinishCreateView` i put: in `    def get(self, request, *args, **kwargs):` 
```
account.account = request.user
account.save()
```
